logging:
  level:
    br.com.cooperativism: ${API_LOG_LEVEL:DEBUG}
    org.springframework:
      boot.context: INFO

server:
  compression:
    enabled: true
  context-path: /
  port: ${SERVER_PORT:8000}

documentation:
  info:
    title: Api Cooperativismo
    description: Gerenciamento de Assembleias - controle de votação.
  version: ~project.version~
  base-package: br.com.cooperativism.controller

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  cache:
    type: redis
  datasource:
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:cooperativism}?reconnect=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    tomcat:
      test-on-borrow: true
      test-on-connect: true
      validation-query: SELECT 1 FROM DUAL
      init-s-q-l: SELECT 1 FROM DUAL
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: ${MQ_PORT:5672}
    username: ${MQ_USER:mquser}
    password: ${MQ_PASSWORD:mq1234567}
    virtual-host: cooperativism
    queue: vote-queue
    exchange: cooperativism-exchange
    deadQueue: vote-dead-queue
    connection-timeout: 15000
    listener:
      simple:
        default-requeue-rejected: false

api:
  user: https://user-info.herokuapp.com/users
